### ISSUE TITLE
Crafting the leather backpack seems to crash the game (v0.7.5-BETA | tested in SP and MP, 1.21, fabric 1.16.0)

### ISSUE THREAD

**Issue by rght925h** [Stein-N/Resource-Backpacks#11]
When crafting the default backpack via a crafting bench, the game crashes as soon as all ingredients are placed.

Exit message:

```
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.xstopho.resource_backpacks.components.BackpackContainerContent.stream()" because "containerContent" is null
```

log entry:

```
Time: 2024-08-15 18:45:04
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.xstopho.resource_backpacks.components.BackpackContainerContent.stream()" because "containerContent" is null
	at net.xstopho.resource_backpacks.compat.shulkerboxtooltip.BackpackPreviewProvider.getInventory(BackpackPreviewProvider.java:22)
	at net.xstopho.resource_backpacks.compat.shulkerboxtooltip.BackpackPreviewProvider.shouldDisplay(BackpackPreviewProvider.java:15)
	at com.misterpemodder.shulkerboxtooltip.ShulkerBoxTooltipClient.getTooltipHints(ShulkerBoxTooltipClient.java:56)
	at com.misterpemodder.shulkerboxtooltip.ShulkerBoxTooltipClient.modifyStackTooltip(ShulkerBoxTooltipClient.java:148)
	at net.minecraft.class_1799.handler$gng000$shulkerboxtooltip$onGetTooltip(class_1799.java:6136)
	at net.minecraft.class_1799.method_7950(class_1799.java:807)
	at net.minecraft.class_437.method_25408(class_437.java:243)
	at net.minecraft.class_465.method_51454(class_465.java:187)
	at net.minecraft.class_465.method_2380(class_465.java:182)
	at net.minecraft.class_479.method_25394(class_479.java:62)
	at dev.imb11.flow.render.RenderHelper.cacheScreen(RenderHelper.java:126)
	at net.minecraft.class_465.redirect$dep000$flow$$render_animation(class_465.java:6307)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_479.method_25394(class_479.java:57)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$272(class_757.java)
	at net.minecraft.class_757.wrapOperation$dbi000$fabric-screen-api-v1$onRenderScreen(class_757.java:4586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

This is the single most elegant and functional backpack mod, by the way. Many thanks for that - love it! :-)

**Comment by Stein-N** [comment]
Hey sry for the late response, didnt noticed the issue, it is fixed now with version 0.7.6-BETA.
