### ISSUE TITLE
[Fabric] Network Protokoll Error 

### ISSUE THREAD

**Issue by ITTV-tools** [Stein-N/Resource-Backpacks#27]
### Mod loader

Fabric

### Mod version

0.10.2

### Minecraft version

1.21.4

### Issue description

When I try to open a backpack, I loose connection to the server. 
Connection lost
Network Protokoll Error
`[21:03:29] [Render thread/ERROR]: Failed to handle packet net.minecraft.class_2649@d229bad, disconnecting
java.lang.IndexOutOfBoundsException: Index 69 out of bounds for length 69
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at knot/net.minecraft.class_2371.get(class_2371.java:47) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1703.method_7611(class_1703.java:313) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1703.method_7610(class_1703.java:642) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_634.method_11153(class_634.java:1355) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2649.method_11439(class_2649.java:51) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2649.method_65081(class_2649.java:12) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1296) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:922) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:267) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]`

### If Bug

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

**Comment by Stein-N** [comment]
Do you try to open the backpack via KeyBind or by right clicking it when it is in hand or when it is placed?
Because i cant reproduce the disconnect?

**Comment by ITTV-tools** [comment]
Right click while it stands on the ground. I see the inventory for a split secound and then it disconnects.

**Comment by Stein-N** [comment]
Please can you export your Minecraft instance in prism launcher and upload the zip file here?

**Comment by ITTV-tools** [comment]
I can. https://filebin.net/idgax4i2ffz92j8v. But I noticed this happens only on my server. Not if is create a single player world

**Comment by ITTV-tools** [comment]
One more thing. I added the mod after I created the server

**Comment by Stein-N** [comment]
> One more thing. I added the mod after I created the server

this shouldnt be an issue, but all i can say is that i cant reproduce the disconnect, might be an incompatibility with one of the other mods, i will have a look at this tomorrow

**Comment by Stein-N** [comment]
OK sins the last version i already made changes, would you test this snapshot version and test if the bugs/disconnects still happen?

https://raw.githubusercontent.com/Stein-N/resources/main/snapshots/Resource Backpacks/resource_backpacks-fabric-1.21.4-0.10.3-BETA.jar

**Comment by ITTV-tools** [comment]
Still same issue

**Comment by Stein-N** [comment]
So after more testing, also with different configs on server and client and talking with other devs i can't find any cause for that disconnects, so there might happen something on you PC/Server or with your Minecraft instance that isn't reproducable at my end.

So this issue will not be investigated further, sry for that.

**Comment by Stein-N** [comment]
With the version 0.11.5-BETA the Menu Handling was partially redone so this issue should be fixed also related to the latest network/gui issue #35
