### ISSUE TITLE
[Fabric] Network Protocol Error

### ISSUE THREAD

**Issue by Bhopperthepaster** [Stein-N/Resource-Backpacks#29]
### Mod loader

Fabric

### Mod version

v0.10.2 BETA

### Minecraft version

1.21.4

### Issue description

Basically, when using this mod with Ambient Sounds (https://www.curseforge.com/minecraft/mc-mods/ambientsounds), then using the backpacks disconnects me and the leather one is really buggy.

---- Minecraft Network Protocol Error Report ----
// Are you sure you are not moving wrongly?

Time: 2024-12-14 15:24:15
Description: Packet handling error

java.lang.IndexOutOfBoundsException: Index 120 out of bounds for length 120
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at knot//net.minecraft.class_2371.get(class_2371.java:47)
	at knot//net.minecraft.class_1703.method_7611(class_1703.java:313)
	at knot//net.minecraft.class_1703.method_7610(class_1703.java:642)
	at knot//net.minecraft.class_634.method_11153(class_634.java:1355)
	at knot//net.minecraft.class_2649.method_11439(class_2649.java:51)
	at knot//net.minecraft.class_2649.method_65081(class_2649.java:12)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1296)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at knot//net.minecraft.class_2371.get(class_2371.java:47)
	at knot//net.minecraft.class_1703.method_7611(class_1703.java:313)
	at knot//net.minecraft.class_1703.method_7610(class_1703.java:642)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:container_set_content
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:56)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:131)
	at knot//net.minecraft.class_8673.method_59807(class_8673.java:110)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:32)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1296)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Is Local: false
	Server type: OTHER
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 257434856 bytes (245 MiB) / 637534208 bytes (608 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 630
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.2121
	Graphics card #1 name: NVIDIA GeForce GTX 1050
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 4096.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 18768.70
	Virtual memory used (MiB): 12775.27
	Swap memory total (MiB): 10684.54
	Swap memory used (MiB): 2777.12
	Space in storage for jna.tmpdir (MiB): available: 58474.65, total: 998090.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 58474.65, total: 998090.00
	Space in storage for io.netty.native.workdir (MiB): available: 58474.65, total: 998090.00
	Space in storage for java.io.tmpdir (MiB): available: 58474.65, total: 998090.00
	Space in storage for workdir (MiB): available: 58474.65, total: 998090.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.1.3
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		collective: Collective 7.89
		creativecore: CreativeCore 2.12.22
			net_neoforged_bus: bus 7.2.0
		fabric-api: Fabric API 0.112.0+1.21.4
			fabric-api-base: Fabric API Base 0.4.53+453d4f9104
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.85+b1caf1e904
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.5+b1caf1e904
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.7+7feeb73304
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.28+20ea1e2304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.61+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.40+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.78+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.13+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.7+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.7+b1caf1e904
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.4+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.2.0+20ea1e2304
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.11+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.1+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.13+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.22+7feeb73304
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.56+7feeb73304
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.54+df3654b304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.3+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.32+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.20+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.24+7feeb73304
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 4.1.0+7b6b225304
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.8+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.6+e604fe7f04
			fabric-particles-v1: Fabric Particles (v1) 4.0.13+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.4+b1caf1e904
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.0+9ba00ebb04
			fabric-renderer-api-v1: Fabric Renderer API (v1) 5.0.1+84404cdd04
			fabric-renderer-indigo: Fabric Renderer - Indigo 2.0.1+84404cdd04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.18+7feeb73304
			fabric-rendering-v1: Fabric Rendering (v1) 10.1.1+b874120c04
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.11+b1caf1e904
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.37+7feeb73304
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.107+7feeb73304
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.32+7feeb73304
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.1+20ea1e2304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.7+b1caf1e904
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fullbrightnesstoggle: Full Brightness Toggle 4.2
		iris: Iris 1.8.4+mc1.21.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		logical_zoom: Logical Zoom 0.0.28
		minecraft: Minecraft 1.21.4
		modmenu: Mod Menu 13.0.0-beta.1
			placeholder-api: Placeholder API 2.5.1+1.21.3
		notenoughanimations: NotEnoughAnimations 1.8.2
		resource_backpacks: Resource Backpacks 0.10.2-BETA
		resourceconfigapi: Resource Config API 1.21-2.1.5
		resourcelibrary: Resource Library 1.21.4-2.3.3
		sodium: Sodium 0.6.3+mc1.21.4
		sound_physics_remastered: Sound Physics Remastered 1.21.4-1.4.7
	Loaded Shaderpack: (off)

### If Bug

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Provide the latest.log file

https://pastebin.com/YSLH47r5

**Comment by Stein-N** [comment]
Do you play in an Singleplayer World or on a server?

How do u interact with the Backpack right click from inventory or when it is placed or even with keybind when it is equipped in the chest slot?

What specifically is buggy about the Leather Backpack?

Did you tested it on a Minecraft Instance with only AmbientSounds and ResourceBackpacks?

Because like on #27 i cant reproduce the Disconnect or any Network error, tested it on local and server.

**Comment by Bhopperthepaster** [comment]
Hello, so I'm playing on a server hosted locally. The mod files are exactly the same for both the client and the server.

I'm placing the backpack on the ground and I try to interact with it. I'm going to upload a video and post it on streamable and I will send the link in a following comment. 

The leather backpack is buggy meaning that instead of the small size it becomes like the netherite one and my inventory is somehow inside it, but they are all like some ghost items, which you can only visually get into/out the backpack, but it's still really weird (you will see in the video I will send).

I've tested removing all my mods and trying to add each one 1 by 1 and checking if it made the backpacks broken. When I got to the AmbientSounds mod, I added it and hopped on the server. When I tried opening the leather backpack, the thing that I mentioned earlier is happening.

**Comment by Stein-N** [comment]
OK sins the last version i already made changes, would you test this snapshot version and test if the bugs/disconnects still happen?

https://raw.githubusercontent.com/Stein-N/resources/main/snapshots/resource_backpacks/resource_backpacks-fabric-1.21.4-0.10.3-BETA.jar

**Comment by Bhopperthepaster** [comment]
So, tried the version that you just sent, same things happen. I'm also sending the link to the video, it's exporting rn.

---- Minecraft Network Protocol Error Report ----
// Too many suspicious packets

Time: 2024-12-14 17:59:55
Description: Packet handling error

java.lang.IndexOutOfBoundsException: Index 45 out of bounds for length 45
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at knot//net.minecraft.class_2371.get(class_2371.java:47)
	at knot//net.minecraft.class_1703.method_7611(class_1703.java:313)
	at knot//net.minecraft.class_1703.method_7610(class_1703.java:642)
	at knot//net.minecraft.class_634.method_11153(class_634.java:1355)
	at knot//net.minecraft.class_2649.method_11439(class_2649.java:51)
	at knot//net.minecraft.class_2649.method_65081(class_2649.java:12)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1296)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at knot//net.minecraft.class_2371.get(class_2371.java:47)
	at knot//net.minecraft.class_1703.method_7611(class_1703.java:313)
	at knot//net.minecraft.class_1703.method_7610(class_1703.java:642)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:container_set_content
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:56)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:131)
	at knot//net.minecraft.class_8673.method_59807(class_8673.java:110)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:32)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1296)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Is Local: false
	Server type: OTHER
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 142497456 bytes (135 MiB) / 570425344 bytes (544 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 630
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.2121
	Graphics card #1 name: NVIDIA GeForce GTX 1050
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 4096.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 20842.75
	Virtual memory used (MiB): 17744.07
	Swap memory total (MiB): 12758.59
	Swap memory used (MiB): 4816.79
	Space in storage for jna.tmpdir (MiB): available: 54630.86, total: 998090.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 54630.86, total: 998090.00
	Space in storage for io.netty.native.workdir (MiB): available: 54630.86, total: 998090.00
	Space in storage for java.io.tmpdir (MiB): available: 54630.86, total: 998090.00
	Space in storage for workdir (MiB): available: 54630.86, total: 998090.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.1.3
		creativecore: CreativeCore 2.12.22
			net_neoforged_bus: bus 7.2.0
		fabric-api: Fabric API 0.112.0+1.21.4
			fabric-api-base: Fabric API Base 0.4.53+453d4f9104
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.85+b1caf1e904
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.5+b1caf1e904
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.7+7feeb73304
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.28+20ea1e2304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.61+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.40+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.78+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.13+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.7+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.7+b1caf1e904
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.4+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.2.0+20ea1e2304
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.11+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.1+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.13+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.22+7feeb73304
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.56+7feeb73304
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.54+df3654b304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.3+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.32+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.20+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.24+7feeb73304
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 4.1.0+7b6b225304
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.8+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.6+e604fe7f04
			fabric-particles-v1: Fabric Particles (v1) 4.0.13+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.4+b1caf1e904
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.0+9ba00ebb04
			fabric-renderer-api-v1: Fabric Renderer API (v1) 5.0.1+84404cdd04
			fabric-renderer-indigo: Fabric Renderer - Indigo 2.0.1+84404cdd04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.18+7feeb73304
			fabric-rendering-v1: Fabric Rendering (v1) 10.1.1+b874120c04
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.11+b1caf1e904
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.37+7feeb73304
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.107+7feeb73304
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.32+7feeb73304
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.1+20ea1e2304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.7+b1caf1e904
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.4
		modmenu: Mod Menu 13.0.0-beta.1
			placeholder-api: Placeholder API 2.5.1+1.21.3
		resource_backpacks: Resource Backpacks 0.10.3-BETA
		resourceconfigapi: Resource Config API 1.21-2.1.5
		resourcelibrary: Resource Library 1.21.4-2.3.3

**Comment by Bhopperthepaster** [comment]
https://streamable.com/38rwtv

Here's the link to the video.

**Comment by Stein-N** [comment]
With the sended version the ghost items also happen?

**Comment by Bhopperthepaster** [comment]
> With the sended version the ghost items also happen?

yep
![image](https://github.com/user-attachments/assets/0e5ba755-9f49-4e10-b93e-d1161327452f)
https://streamable.com/8v9kkh

**Comment by Bhopperthepaster** [comment]
Also these are the mods on the server.
![image](https://github.com/user-attachments/assets/2c3753b8-7f88-4c27-bab7-1368266b4ec5)

Edit 1 : Tested on singleplayer aswell, it works fine there.

Edit 2 : Added the AmbientSounds mod to the server aswell and the backpacks work as intended. But it's weird still because the AmbientSounds mod is client-side only, so I don't see why if the mod is on the server then the backpacks work.

**Comment by Stein-N** [comment]
Honestly i don't have clue what is triggering this issues, because i can't reproduce the bugs/disconnects. I will look tomorrow again, if there is something i didn't saw today.

The only bug i know, that should be fixed with this version, was the duplication glitch of the ender chest into other backpacks.

**Comment by Bhopperthepaster** [comment]
If you have discord and want to I can show you the exact stuff I have in the server and minecraft, here's mine: **auxl.** , I'll accept the friend request.

**Comment by Stein-N** [comment]
So after more testing, also with different configs on server and client and talking with other devs i can't find any cause for that disconnects or even with the ghosting of items, so there might happen something on you PC or with your Minecraft instance that isn't reproducable at my end.

So this issue will not be investigated further, sry for that.

**Comment by Stein-N** [comment]
With the version 0.11.5-BETA the Menu Handling was partially redone so this issue should be fixed also related to the latest network/gui issue #35
